name: "05: Deploy to Production"

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        default: "1.0"
        description: "the major and minor version"
      runDbMigration:
        required: false
        type: string
        default: "false"
        description: "should the db migration be executed after the deployment?"

concurrency:
  group: "deployment"

jobs:
  build:
    uses: aduyng/sabre-spot-the-dot/.github/workflows/build-fn.yml@master
    with:
      VERSION: ${{ github.event.inputs.version }}.${{github.run_number}}

  deploy:
    needs:
      - build
    uses: aduyng/sabre-spot-the-dot/.github/workflows/deploy-fn.yml@master
    with:
      GCP_REGION: "us-central1"
      LOG_LEVEL: "info"
      FIREBASE_API_KEY: "AIzaSyDbPR1cFfplX8xbKZ46TqUv6AFiB_8eivc"
      FIREBASE_AUTH_DOMAIN: "sabre-spot-the-dot.firebaseapp.com"
      FIREBASE_DATABASE_URL: "https://sabre-spot-the-dot-default-rtdb.firebaseio.com"
      FIREBASE_APP_ID: "1:498303805680:web:3597434a410bbae011ba35"
      FIREBASE_PROJECT_ID: "sabre-spot-the-dot"
      FIREBASE_STORAGE_BUCKET: "sabre-spot-the-dot.appspot.com"
      FIREBASE_MESSAGING_SENDER_ID: "205994041605"
      POSTGRES_INSTANCE_CONNECTION_NAME: "sabre-spot-the-dot:us-central1:spot-the-dot"
      POSTGRES_DB: "spot-the-dot"
      POSTGRES_USER: "sabre"
      STD_RUNTIME_ENV: "production"
      STD_VERSION: ${{ github.event.inputs.version }}.${{github.run_number}}
      SQL_DEBUG: "true"
      STD_FRONTEND_BASE_URL: "https://sabre-spot-the-dot.web.app/"
      SHOULD_RUN_DB_MIGRATION: ${{ github.event.inputs.runDbMigration }}
    secrets:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      POSTGRES_PASSWORD: "${{ secrets.POSTGRES_PASSWORD }}"

